spring.application.name=spring-boot
spring.datasource.url=jdbc:postgresql://localhost:5442/odms
server.port=8083
spring.datasource.password=password
spring.datasource.username=liz
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.JBossASJtaPlatform
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
spring.main.allow-bean-definition-overriding=true